---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.docker_registry }}/{{ .Values.name }}:{{ .Values.rev }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: 32Mi
            limits:
              memory: 64Mi
          ports:
            - containerPort: {{ .Values.port }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.port }}
          env:
            - name: FORCE_UPDATE
              value: "{{ .Values.force_update | default 0 }}"
            {{- range $key, $value := .Values }}{{ if hasPrefix "env_" $key }}
            - name: {{ $key | trimPrefix "env_" }}
              value: "{{ $value }}"
            {{- end }}{{- end }}